internBlog/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace internBlog.Models
{
    public class Comment
    {
        public int cid { get; set; }

        public int postId { get; set; }
        public string cuser { get; set; }   
        public string cbody { get; set; }
        public DateTime cpostDate { get; set; }
    }
}

internBlog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace internBlog.Models
{
    public class Post
    {
        public int pid { get; set; }
        public string ptitle { get; set; }
        public string pbody { get; set; }   
        public string pauthor { get; set; }
        public string pimagePath { get; set; }
        public DateTime ppostDate { get; set; }
        public DateTime pupdatedDate { get; set; }
    }
}

internBlog/Models/PostDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace internBlog.Models
{
    public class PostDetails
    {
        public int pid { get; set; }
        public string ptitle { get; set; }
        public string pbody { get; set; }
        public string pauthor { get; set; }
        public string pimagePath { get; set; }
        public DateTime ppostDate { get; set; }
        public DateTime pupdatedDate { get; set; }
        public int cid { get; set; }
        public string cuser { get; set; }
        public string cbody { get; set; }
        public DateTime cpostDate { get; set; }

    }
}

internBlog/Controllers/PostController.cs
using internBlog.Models;
using internBlog.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace internBlog.Controllers
{
    public class PostController : Controller
    {
        PostRepository postRepository = new PostRepository();
        // GET: Post
        public ActionResult Index()
        {
            //var listPost = postRepository.GetAllPosts();
            return View();
        }

        public ActionResult TestView()
        {
            return View();
        }

        public JsonResult GetList()
        {
            var listPost = postRepository.GetAllPosts().Select(s => new
            {
                pid = s.pid,
                ptitle = s.ptitle,
                pbody = s.pbody,
                pauthor = s.pauthor,
                pimagePath = s.pimagePath,
                ppostDate = s.ppostDate.ToShortDateString(),
            }).ToList();
            return Json(listPost, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult InsertPost()
        { 
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public JsonResult InsertPost(HttpPostedFileBase ImageFile, Post p)
        {
            string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string fileExtension = Path.GetExtension(ImageFile.FileName);
            fileName = fileName + fileExtension;
            p.pimagePath = "/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            ImageFile.SaveAs(fileName);
            postRepository.InsertPost(p);
            return Json(JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeletePost(Post p)
        {
            postRepository.DeletePost(p);
            return Json(JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult PostDetail(int id)
        {
            var postDetails = postRepository.PostDetail(id);
            return Json(postDetails, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult PostDetail(PostDetails postDetails)
        {
            postRepository.InsertComment(postDetails);
            return Redirect("./" + postDetails.pid);
        }

        [ValidateInput(false)]
        public JsonResult UpdatePost(HttpPostedFileBase ImageFile, Post p)
        {
            if(ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
                string extension = Path.GetExtension(ImageFile.FileName);
                fileName  += extension;
                p.pimagePath = "/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                ImageFile.SaveAs(fileName);
            }
            postRepository.UpdatePost(p);
            return Json(JsonRequestBehavior.AllowGet);
        }

    }
}

internBlog/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

internBlog/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

internBlog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

internBlog/Views/Post/Index.cshtml
@model IEnumerable<internBlog.Models.Post>



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Blogs</h2>
@Html.ActionLink("Create New", "InsertPost", null, null, new { @class = "btn btn-info d-inline" })



@if (Model != null)
{
    <div class="container">
        @foreach (var item in Model)
        {
            <h1>@Html.DisplayFor(modelItem => item.ptitle)</h1>
            <p>@Html.DisplayFor(modelItem => item.pauthor), @Html.DisplayFor(modelItem => item.ppostDate)</p>
            <p>@Html.DisplayFor(modelItem => item.pbody)</p>
            <p>@Html.ActionLink("Read more.....", "PostDetail", new { id = item.pid })</p>
            <hr />
        }
    </div>
}


<div class="">
    <div class="modal fade bd-example-modal-lg" id="blog-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content p-4">
                <div id="blog-title">
                </div>
                <div id="blog-body">
                </div>
                <div id="submit-button">

                </div>
                <button class="btn btn-primary" onclick="submitPost()">Submit</button>
            </div>
        </div>
    </div>
    <div class="modal fade bd-example-modal-lg" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content p-4">
                <h3>Are you sure about deleting post?</h3>
                <p>
                    <button class="btn btn-primary" onclick="hideDeleteModal()">Cancel</button>
                    <button class="btn btn-danger" onclick="deletePost()">Delete</button>
                </p>
            </div>
        </div>
    </div>
    <div id="blogs">

    </div>

</div>




@section scripts{
    @using System.Web.Optimization
    @Scripts.Render("~/bundles/jqueryval")


    <script>
        $(document).ready(function () {
            getList();
        });

        function getList() {
            $.ajax({
                url: '/Post/GetList',
                method: 'get',
                dataType: 'json',
                success: function (data) {
                    var es = '';
                    var i = 1;
                    $.each(data, function (key, item) {
                        console.log(i);
                        es += `<br />
                                <div id="title"><h1>` + item.ptitle + `</h1></div>
                                <div id="image">
                                    <img class="img-fluid" src="`+ item.pimagePath + `">
                                </div>
                                <div class="d-flex justify-content-between">
                                    <p id="author">` + item.pauthor + `</p>
                                    <p id="date">` + item.ppostDate + `</p>
                                </div>
                                <div id="body">` + item.pbody.substring(0, 250) + `...</div>
                                <input type="hidden" id="pid" value=`+ item.pid + `></input>
                                <div>
                                    <button class='btn btn-primary' onclick='detailPost()'>Details</button>
                                    <button class='btn btn-info' onclick='updatePost()'>Update</button>
                                    <button class='btn btn-danger' onclick='showDeleteModal()'>Delete</button>
                                </div><br>`;
                        i++;
                    });
                    if (data.length === 0) {
                        es += `<center><h1> No posts added :(</h1></center>`;
                    }
                    $('#blogs').html(es);
                },
                error: function (error) {
                    console.log("Hello! error has occurred");
                }
            });
        }

        function submitPost() {
            var formData = new FormData();
            let pid = $('#pid').val().trim();
            let ptitle = $('#ptitle').val().trim();
            let pbody = $('#pbody').val().trim();
            let pimagePath = $('#ppathImage').val().trim();
            let imageFile = document.getElementById("ppathImage").files[0];
            console.log(pimagePath);
            if (pimagePath == '') {
                console.log("no image selected");
                pimagePath = $('#oldImagePath').attr('src');
            } 
            if (ptitle === '') {
                toastr.error("Please fill out the title.");
            } else if (pbody === '') {
                toastr.error("Please fill out the body.");
            } else {
                formData.append('pid', pid);
                formData.append('ptitle', ptitle);
                formData.append('pbody', pbody);
                formData.append('pimagePath', pimagePath);
                formData.append('imageFile', imageFile);
                $.ajax({
                    url: '/Post/UpdatePost',
                    method: 'post',
                    dataType: 'json',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        toastr.success("Post updated!");
                        $('#blog-modal').modal('hide');
                        getList();

                    },
                    error: function (request, status, error) {
                        toastr.error("error has occurred!");
                        console.log(error);
                    }
                });
            }
        }

        function detailPost() {
            let pid = $('#pid').val().trim();
            $.ajax({
                url: '/Post/PostDetail?id=' + pid,
                method: 'get',
                success: function (data) {
                    let title = `<h1>` + data[0].ptitle + `</h1>`;
                    let body = `<p>` + data[0].pbody + `</p>`;
                    $('#blog-title').html(title);
                    $('#blog-body').html(body);
                    $('#blog-modal').modal('show');
                },
                error: function (error) {
                    toastr.error("Error occurred while opening post.");
                    console.log(error);
                }
            });
        }

        function updatePost() {
            let pid = $('#pid').val().trim();
            $.ajax({
                url: '/Post/PostDetail?id=' + pid,
                method: 'get',
                success: function (data) {
                    var titleField = `<h2>Title</h2><input class="form-control" type="text" id="ptitle" value="` + data[0].ptitle + `" />`;
                    var bodyField = `<h2>Body</h2>
                                        <input class="form-control" type="file" id="ppathImage" accept="image/*" />
                                        <img id="oldImagePath" class="img-fluid" src="`+ data[0].pimagePath + `">
                                        <textarea class="form-control" type="text" id="pbody" rows="10">` + data[0].pbody + `</textarea>`;
                    $('#blog-title').html(titleField);
                    $('#blog-body').html(bodyField);
                    $('#blog-modal').modal('show');
                },
                error: function (error) {
                    toastr.error("Error occurred while opening post.");
                    console.log(error);
                }
            });
        }

        function showDeleteModal() {
            $("#delete-modal").modal('show');
        }

        function hideDeleteModal() {
            $("#delete-modal").modal('hide');
        }

        function deletePost() {
            let pid = $('#pid').val().trim();
            data = {
                pid,
            }
            $.ajax({
                url: '/Post/DeletePost',
                method: 'post',
                dataType: 'json',
                data: data,
                success: function () {
                    toastr.success("Post deleted!");
                    hideDeleteModal();
                    getList();
                },
                error: function () {
                    toastr.error("Error occurred while deleting post.");
                }
            });
        }
    </script>

}

internBlog/Views/Post/InsertPost.cshtml
@model internBlog.Models.Post

@{
    ViewBag.Title = "InsertPost";
}

<h2>InsertPost</h2>

<div class="form-horizontal">
    <h4>Post</h4>
    <hr />
    <div class="form-group">
        <h5>Title</h5>
        <input class="form-control" type="text" id="ptitle" />
    </div>
    <div class="form-group">
        <h5>Image</h5>
        <input class="form-control" type="file" id="ppathImage" accept="image/*"/>
    </div>
    <div class="form-group">
        <h5>Body</h5>
        <textarea class="form-control" type="text" id="pbody"></textarea>
    </div>
    <div class="form-group">
        <h5>Author</h5>
        <input class="form-control" type="text" id="pauthor" />
    </div>
    <br />

</div>

<div>
    <button class="btn btn-primary" onclick="submitPost()">Submit</button>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
</div>


@section scripts{
    @using System.Web.Optimization
    @Scripts.Render("~/bundles/jqueryval")


<script>
    function submitPost() {
        var formData = new FormData();
        let ptitle = $('#ptitle').val().trim();
        let pbody = $('#pbody').val().trim();
        let pauthor = $('#pauthor').val().trim();
        let pimagePath = $('#ppathImage').val().trim();
        let imageFile = document.getElementById("ppathImage").files[0];
        if (ptitle === '') {
            toastr.error("Please fill out the title.");
        } else if (pbody === '') {
            toastr.error("Please fill out the body.");
        } else if (pauthor === '') {
            toastr.error("Please fill out the author name.");
        } else if (ppathImage === '') {
            toastr.error("Please select a image.");
        } else {
            formData.append('ptitle', ptitle);
            formData.append('pbody', pbody);
            formData.append('pauthor', pauthor);
            formData.append('pimagePath', pimagePath);
            formData.append('imageFile', imageFile);
            $.ajax({
                url: '/Post/InsertPost',
                method: 'post',
                dataType: 'json',
                data: formData,
                //contentType: 'multipart/form-data',
                contentType: false,
                processData: false,
                success: function (data) { 
                    toastr.success("Post added!");
                    reset();
                },
                error: function (request, status, error) {
                    toastr.error("error has occurred!");
                    console.log(error);
                }
            });
        }
    }
                    
    function reset() {
        $('#ptitle').val('');
        $('#pbody').val('');
        $('#pauthor').val('');
    }
    ////$(document).ready(function () {
    ////    function submitPost() {
    ////        let ptitle = $('#ptitle').val().trim();
    ////        let pbody = $('#pbody').val().trim();
    ////        let pauthor = $('#pauthor').val().trim();
    ////        if (ptitle === '') {
    ////            toastr.error("Please fill out the title.");
    ////        } else if (pbody === '') {
    ////            toastr.error("Please fill out the body.");
    ////        } else if (pauthor === '') {
    ////            toastr.error("Please fill out the author name.");
    ////        }
    ////    }
    ////});
</script>

}

internBlog/Views/Post/PostDetail.cshtml
@model IEnumerable<internBlog.Models.PostDetails>

@{
    ViewBag.Title = "PostDetail";
    int postId = Model.First().pid;
    string cuser = "Kiran";
}

@if (Model.Count() > 0)
{
    <h1>@Html.DisplayFor(modelItem => Model.First().ptitle)</h1>
    <p>@Html.DisplayFor(modelItem => Model.First().pauthor), @Html.DisplayFor(modelItem => Model.First().ppostDate)</p>
    <p>@Html.DisplayFor(modelItem => Model.First().pbody)</p>
    <hr />
    <h4>Comments</h4>
    <form method="post">
        <div class="form-group">
            <p><input class="form-control" name="cbody" type="text" placeholder=""></p>
            <p><input class="form-control" name="pid" type="hidden" placeholder="" value=@Model.First().pid></p>
            <p><input class="form-control" name="cuser" type="hidden" placeholder="" value=@cuser></p>
            <input type="submit" value="Comment" class="btn btn-primary" />
        </div>
    </form>
}

<div class="container">
    @foreach (var item in Model)
    {
        if (item.cbody != null)
        {
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <p>@Html.DisplayFor(modelItem => item.cuser)</p>
                    </div>
                    <div class="card-text">
                        <p>@Html.DisplayFor(modelItem => item.cbody)</p>
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Delete", "DeleteComment", null, null, new { @class = "btn btn-danger" }) &nbsp; &nbsp; &nbsp; &nbsp; @Html.DisplayFor(modelItem => item.cpostDate)
                </p>
            </div>
            <hr />

        }
        else
        {
            <p>No comments yet. :(</p>
        }

    }
</div>



@section scripts{
    @using System.Web.Optimization
    @Scripts.Render("~/bundles/jqueryval")


    <scripts>

    </scripts>

}

internBlog/Views/Post/TestView.cshtml
@{
    ViewBag.Title = "TestView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TestView</h2>

internBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <div class="navbar-brand">
                @Html.ActionLink("Very good blog", "Index", "Post", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Post", new {@class = "nav-link"})</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr.min.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>